const errorMessages: Record<string, string> = {
  "11": "A duplicate transaction has been submitted",
  "13": "Invalid Merchant Login ID or Password or Inactive Account",
  "14": "Invalid Referrer or Relay Response URL",
  "16": "Transaction Not Found",
  "17": "Merchant Does Not Accept This Type of Card",
  "27": "Invalid address",
  "28": "Merchant Does Not Accept This Type of Card",
  "39": "Invalid or Unsupported Currency Code",
  "52": "Unable to Send Notification to Customer",
  "63": "Processing Error",
  "66": "Transaction Not Accepted for Processing",
  "87": "Transactions of This Market Type Cannot Be Processed on This System",
  "92": "Unsupported Method of Integration",
  "97": "Transaction Cannot Be Accepted",
  "98": "This transaction cannot be accepted.",
  "99": "This transaction cannot be accepted.",
  "123": "This account has not been given the permissions required for this request.",
  "127": "Could Not Void",
  "180": "Voiding credits is not permitted by the processor.",
  "312": "Invalid Security Code",
  "313": "This error indicates that the customer has requested a new Security Code.",
  "325": "Required fields are missing from the request.",
  "326": "Invalid data in one or more request fields.",
  "327": "Void request was unsuccessful.",
  "401":"API key not provided or invalid API key used.",
  "404":"Unrecognized request URL",
  "405":"The HTTP method is not applicable for this API",
  "422":"Please pass the data in the expected format",
  "400" :"Ensure the webhook body is correctly formatted and try again.",
  "500":"Please try again later. If the issue persists",
    "IR_00": "This API is currently under development. Please check back soon.",
    "IR_01": "API key is missing or invalid. Please provide a valid API key in the Authorization header.",
    "IR_02": "The request URL is unrecognized. Please verify and use the correct URL.",
    "IR_03": "The HTTP method used is not applicable for this API. Please check the method in the documentation.",
    "IR_04": "The request is missing a required parameter. Please ensure all necessary parameters are included.",
    "IR_05": "Invalid data in 'field_name'. Ensure it meets the expected format.",
    "IR_06": "A required message parameter is missing or invalid. Please refer to the API documentation.",
    "IR_07": "The provided value for 'field_name' is invalid. Please check and provide a valid value.",
    "IR_08": "The client secret is missing. Please include the client secret received in the payments/create API response.",
    "IR_09": "The provided client secret does not match the one associated with the payment. Please verify.",
    "IR_10": "The customer has existing mandates or subscriptions. Cancel them before deleting customer data.",
    "IR_11": "The customer has already been redacted. No further action is required.",
    "IR_12": "You have reached the maximum number of refund attempts for this payment.",
    "IR_13": "The refund amount exceeds the original payment amount. Please verify and adjust accordingly.",
    "IR_14": "This payment cannot be processed due to its current status. Verify the payment status.",
    "IR_15": "The provided Ephemeral Key for the customer is invalid. Please provide the correct key.",
    "IR_16": "The request is invalid due to multiple field errors. Refer to the API documentation for required formats.",
    "IR_17": "Access forbidden due to an invalid JWT token. Please provide a valid token.",
    "IR_18": "You are not authorized to update the customer. Please contact your Org. Admin for access.",
    "IR_19": "There is an issue with the provided details. Please check and retry with the correct information.",
    "IR_20": "The requested flow is not supported by the specified connector.",
    "IR_21": "Missing required parameters in the request. Please check the API documentation.",
    "IR_22": "Access forbidden. You are not authorized to access this resource.",
    "IR_23": "The request requires a supported file provider. Please refer to the API documentation.",
    "IR_24": "The provided wallet token for 'wallet_name' is invalid. Please verify the token.",
    "IR_25": "You cannot delete the default payment method. Check the payment method's activation status.",
    "IR_26": "The provided cookie is invalid. Please check your site settings for cookies.",
    "IR_27": "The extended card information does not exist. Please verify the card details.",
    "IR_28": "The currency used is invalid. Please use a valid currency as per the documentation.",
    "IR_29": "The data format for this request is invalid. Please refer to the API documentation.",
    "IR_30": "The merchant connector account is configured with invalid settings. Please correct the configuration.",
    "IR_31": "The card with the provided IIN does not exist. Please verify the IIN.",
    "IR_32": "The provided card IIN length is invalid. Please provide an IIN with 6 or 8 digits.",
    "IR_33": "A required file is missing or invalid in the request. Please ensure it is included.",
    "IR_34": "A valid dispute ID must be included in the request.",
    "IR_35": "The file purpose is not specified or is invalid. Please provide a valid file purpose.",
    "IR_36": "The file content type must be specified and valid. Please verify the content type.",
    "IR_37": "The requested resource does not exist. Please check your request.",
    "IR_38": "Duplicate entries found in the request. Please check for and correct duplicates.",
    "IR_39": "The required payment method is either not configured or incorrectly configured for the connectors.",
    "CE_01": "Payment failed during authorization with the connector. Please retry the payment.",
    "CE_02": "Payment failed during authentication with the connector. Please retry the payment.",
    "CE_03": "The capture attempt failed during processing with the connector. Please retry.",
    "CE_04": "The card data provided is invalid. Please ensure valid card information is used.",
    "CE_05": "The card has expired. Please provide valid card data.",
    "CE_06": "Refund processing failed at the connector. Please retry the refund.",
    "CE_07": "Verification failed during processing with the connector. Please retry the operation.",
    "CE_08": "Dispute operation failed during processing with the connector. Please retry the operation.",
    "CE_09": "Payout validation failed. Please ensure the payout details are correct and retry.",
    "HE_00": "The resource is currently unavailable. Please try again later or contact support.",
    "HE_01": "The requested operation for the identifier already exists. Please verify the details.",
    "HE_02": "The requested object does not exist in our records. Please verify the details.",
    "HE_03": "Validation failed for the requested operation with the provided details. Please check again.",
    "HE_04": "The requested object does not exist in our records. Please verify the details.",
    "HE_05": "Missing or invalid tenant details. Please verify and try again.",
    "WE_01": "Webhook authentication failed. Please verify your authentication credentials.",
    "WE_02": "A bad request was received in the webhook. Please check the request parameters and format.",
    "WE_03": "There was an issue processing the webhook. Please try again later or contact support.",
    "WE_04": "The webhook resource was not found. Ensure the URL is correct.",
    "WE_05": "The webhook body could not be processed. Ensure it is correctly formatted.",
    "WE_06": "The Merchant Secret for webhook source verification is invalid. Please verify and retry."
}; 

export const getErrorMessageById = (errorId: string): string => {
  return errorMessages[errorId] || "Error Processing Payment with unknown error"; // Return the error message or a default message if not found
};
